name: 'Aqua Security Trivy'
description: 'Scans container images for vulnerabilities with Trivy'
author: 'Aqua Security'
inputs:
  image-ref:
    description: 'image reference'
    required: true
  artifact-type:
    description: 'artifact type (image or fs)'
    required: true
    default: "image"
  aritfact-ref:
    description: 'artifact reference (image reference or file path)'
    required: true
  exit-code:
    description: 'exit code when vulnerabilities were found'
    required: false
    default: '0'
  ignore-unfixed:
    description: 'ignore unfixed vulnerabilities'
    required: false
    default: "false"
  vuln-type:
    description: 'comma-separated list of vulnerability types (os,library)'
    required: false
    default: 'os,library'
  severity:
    description: 'severities of vulnerabilities to be displayed'
    required: false
    default: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
  format:
    description: 'output format (table, json, template)'
    required: false
    default: 'table'
  template:
    description: 'use an existing template for rendering output (@/contrib/sarif.tpl, @/contrib/gitlab.tpl, @/contrib/junit.tpl'
    required: false
    default: ''
  output:
    description: 'writes results to a file with the specified file name'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://docker.io/aquasec/trivy:latest'
  args:
    - '${{ inputs.artifact-type }}'
    - '--format=${{ inputs.format }}'
    - '--template=${{ inputs.template }}'
    - '--exit-code=${{ inputs.exit-code }}'
    - '--ignore-unfixed=${{ inputs.ignore-unfixed }}'
    - '--vuln-type=${{ inputs.vuln-type }}'
    - '--severity=${{ inputs.severity }}'
    - '--output=${{ inputs.output }}'
    - '${{ inputs.artifact-ref }}'
