FROM aquasec/trivy:0.24.0
COPY entrypoint.sh /
RUN apk --no-cache add bash
RUN chmod +x /entrypoint.sh

COPY --from=shellspec/shellspec-scratch /opt/shellspec /opt/shellspec
ENV PATH /opt/shellspec/:$PATH

WORKDIR /src
RUN trivy image knqyf263/vuln-image:1.2.3 # Update trivy database before test
ENTRYPOINT ["shellspec"]
COPY ./ /src