name: Secure DockerHub Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-image:latest .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-image:latest'
        format: 'table'
        exit-code: '1'
        severity: 'HIGH,CRITICAL'

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push to DockerHub
      run: |
        docker tag my-image:latest yourusername/my-image:latest
        docker push yourusername/my-image:latest
