name: Sync Trivy Checks

on:
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ github.repository_owner }}/trivy-checks-act
  REGISTRY: ghcr.io

jobs:
  sync-trivy-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Trivy Checks
        run: |
          oras cp ghcr.io/aquasecurity/trivy-checks:1 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest